### PR TITLE
Fix tflint and added new github action

### PR DESCRIPTION
**Pull request by theprashantyadav**
## what
* added new github-action
* update terraform and aws version
* update readme and added github action latest version
* fix tflinbt

## why
* need to update terrform and aws latest version
* need to update github-action
* need to update tflint

### CODE REVIEW

**Review by nikitadugar — COMMENTED** [review]
Please fix tflint warnings

**Review by themaniskshah — APPROVED** [review]
LGTM!

**Review by nileshgadgi — APPROVED** [review]
LGTM!

**Review by vaibhav7797 — COMMENTED** [review]
LGTM!

**Pull request merged**
