### PR TITLE
updated readme.md and github-action version

### PR DESCRIPTION
**Pull request by theprashantyadav**
## what
* update readme.md
* update github-action version 
*  update karpenter version latest
*  update tf and aws version latest

## why
* need to update readme.md
* need to update github-action version 
* need to update karpenter version latest 
* need to update aws and terraform version latest

### CODE REVIEW

**Review by themaniskshah — COMMENTED** [review]
Fix Lints. and role name

**Comment by theprashantyadav** [comment]
> Fix Lints. and role name

sir please check lint issue fixed

**Review by themaniskshah — APPROVED** [review]

**Review by nileshgadgi — APPROVED** [review]
LGTM!

**Review by vaibhav7797 — APPROVED** [review]
LGTM!

**Pull request merged**
